# Generated by Django 4.0.3 on 2022-03-27 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Garden_Tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
