# Generated by Django 4.0.3 on 2022-03-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_garden_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden_tasks',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
