# Generated by Django 4.0.3 on 2022-03-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_garden_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden_tasks',
            old_name='gardener',
            new_name='user',
        ),
    ]
